<a href="https://colab.research.google.com/github/yasvanthika122/ML_Models/blob/main/CatBoostClassification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
train=pd.read_csv("https://raw.githubusercontent.com/ezioauditore-tech/AI/main/datasets/amazon-employee-access-challenge/train.csv")
test=pd.read_csv("https://raw.githubusercontent.com/ezioauditore-tech/AI/main/datasets/amazon-employee-access-challenge/test.csv")

In [ ]:
test.head(10)

,id,RESOURCE,MGR_ID,ROLE_ROLLUP_1,ROLE_ROLLUP_2,ROLE_DEPTNAME,ROLE_TITLE,ROLE_FAMILY_DESC,ROLE_FAMILY,ROLE_CODE
0,1,78766,72734,118079,118080,117878,117879,118177,19721,117880
1,2,40644,4378,117961,118327,118507,118863,122008,118398,118865
2,3,75443,2395,117961,118300,119488,118172,301534,249618,118175
3,4,43219,19986,117961,118225,118403,120773,136187,118960,120774
4,5,42093,50015,117961,118343,119598,118422,300136,118424,118425
5,6,44722,1755,117961,117962,119223,125793,146749,118643,125795
6,7,75834,21135,117961,118343,123494,118054,118054,117887,118055
7,8,4675,3077,117961,118300,120312,124194,124195,118363,124196
8,9,18072,15575,117902,118041,118623,280788,280788,292795,119082
9,10,22680,4474,117961,118446,119064,118321,118448,290919,118322

In [ ]:
train.head(10)

,ACTION,RESOURCE,MGR_ID,ROLE_ROLLUP_1,ROLE_ROLLUP_2,ROLE_DEPTNAME,ROLE_TITLE,ROLE_FAMILY_DESC,ROLE_FAMILY,ROLE_CODE
0,1,39353,85475,117961,118300,123472,117905,117906,290919,117908
1,1,17183,1540,117961,118343,123125,118536,118536,308574,118539
2,1,36724,14457,118219,118220,117884,117879,267952,19721,117880
3,1,36135,5396,117961,118343,119993,118321,240983,290919,118322
4,1,42680,5905,117929,117930,119569,119323,123932,19793,119325
5,0,45333,14561,117951,117952,118008,118568,118568,19721,118570
6,1,25993,17227,117961,118343,123476,118980,301534,118295,118982
7,1,19666,4209,117961,117969,118910,126820,269034,118638,126822
8,1,31246,783,117961,118413,120584,128230,302830,4673,128231
9,1,78766,56683,118079,118080,117878,117879,304519,19721,117880

In [ ]:
train.shape,train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32769 entries, 0 to 32768
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ACTION            32769 non-null  int64
 1   RESOURCE          32769 non-null  int64
 2   MGR_ID            32769 non-null  int64
 3   ROLE_ROLLUP_1     32769 non-null  int64
 4   ROLE_ROLLUP_2     32769 non-null  int64
 5   ROLE_DEPTNAME     32769 non-null  int64
 6   ROLE_TITLE        32769 non-null  int64
 7   ROLE_FAMILY_DESC  32769 non-null  int64
 8   ROLE_FAMILY       32769 non-null  int64
 9   ROLE_CODE         32769 non-null  int64
dtypes: int64(10)
memory usage: 2.5 MB

((32769, 10), None)

In [ ]:
test.shape,test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58921 entries, 0 to 58920
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id                58921 non-null  int64
 1   RESOURCE          58921 non-null  int64
 2   MGR_ID            58921 non-null  int64
 3   ROLE_ROLLUP_1     58921 non-null  int64
 4   ROLE_ROLLUP_2     58921 non-null  int64
 5   ROLE_DEPTNAME     58921 non-null  int64
 6   ROLE_TITLE        58921 non-null  int64
 7   ROLE_FAMILY_DESC  58921 non-null  int64
 8   ROLE_FAMILY       58921 non-null  int64
 9   ROLE_CODE         58921 non-null  int64
dtypes: int64(10)
memory usage: 4.5 MB

((58921, 10), None)

In [ ]:
train.isnull().sum(),test.isnull().sum()

(ACTION              0
 RESOURCE            0
 MGR_ID              0
 ROLE_ROLLUP_1       0
 ROLE_ROLLUP_2       0
 ROLE_DEPTNAME       0
 ROLE_TITLE          0
 ROLE_FAMILY_DESC    0
 ROLE_FAMILY         0
 ROLE_CODE           0
 dtype: int64,
 id                  0
 RESOURCE            0
 MGR_ID              0
 ROLE_ROLLUP_1       0
 ROLE_ROLLUP_2       0
 ROLE_DEPTNAME       0
 ROLE_TITLE          0
 ROLE_FAMILY_DESC    0
 ROLE_FAMILY         0
 ROLE_CODE           0
 dtype: int64)

In [ ]:
train.columns

Index(['ACTION', 'RESOURCE', 'MGR_ID', 'ROLE_ROLLUP_1', 'ROLE_ROLLUP_2',
       'ROLE_DEPTNAME', 'ROLE_TITLE', 'ROLE_FAMILY_DESC', 'ROLE_FAMILY',
       'ROLE_CODE'],
      dtype='object')

In [ ]:

train["ACTION"].unique()

array([1, 0])

In [ ]:
for i in train:
  print(i  ,train[i].nunique())

ACTION 2
RESOURCE 7518
MGR_ID 4243
ROLE_ROLLUP_1 128
ROLE_ROLLUP_2 177
ROLE_DEPTNAME 449
ROLE_TITLE 343
ROLE_FAMILY_DESC 2358
ROLE_FAMILY 67
ROLE_CODE 343

In [ ]:
for i in test:
  print(i  ,test[i].nunique())

id 58921
RESOURCE 4971
MGR_ID 4689
ROLE_ROLLUP_1 126
ROLE_ROLLUP_2 177
ROLE_DEPTNAME 466
ROLE_TITLE 351
ROLE_FAMILY_DESC 2749
ROLE_FAMILY 68
ROLE_CODE 351

In [ ]:
!pip install catboost

Requirement already satisfied: catboost in /usr/local/lib/python3.10/dist-packages (1.2.2)
Requirement already satisfied: graphviz in /usr/local/lib/python3.10/dist-packages (from catboost) (0.20.1)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.10/dist-packages (from catboost) (3.7.1)
Requirement already satisfied: numpy>=1.16.0 in /usr/local/lib/python3.10/dist-packages (from catboost) (1.23.5)
Requirement already satisfied: pandas>=0.24 in /usr/local/lib/python3.10/dist-packages (from catboost) (1.5.3)
Requirement already satisfied: scipy in /usr/local/lib/python3.10/dist-packages (from catboost) (1.11.4)
Requirement already satisfied: plotly in /usr/local/lib/python3.10/dist-packages (from catboost) (5.15.0)
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from catboost) (1.16.0)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=0.24->catboost) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=0.24->catboost) (2023.3.post1)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->catboost) (1.2.0)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib->catboost) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->catboost) (4.46.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->catboost) (1.4.5)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->catboost) (23.2)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->catboost) (9.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->catboost) (3.1.1)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from plotly->catboost) (8.2.3)

In [ ]:
X = train.drop("ACTION",axis=1)#axis=1 column 1
y=train["ACTION"]

In [ ]:
import catboost
from catboost import CatBoostClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)#here we split only train dataset,not for test

In [ ]:

catboost_model = CatBoostClassifier(iterations=500, depth=10, learning_rate=0.05, loss_function='MultiClass', eval_metric='Accuracy', cat_features=[])
catboost_model.fit(X_train, y_train, eval_set=(X_test, y_test), verbose=50)
y_pred = catboost_model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy}")

0:	learn: 0.9419798	test: 0.9423253	best: 0.9423253 (0)	total: 292ms	remaining: 2m 25s
50:	learn: 0.9417128	test: 0.9436985	best: 0.9436985 (1)	total: 6.08s	remaining: 53.6s
100:	learn: 0.9419798	test: 0.9436985	best: 0.9436985 (1)	total: 10.9s	remaining: 43.2s
150:	learn: 0.9439634	test: 0.9440037	best: 0.9441562 (143)	total: 14.4s	remaining: 33.4s
200:	learn: 0.9457944	test: 0.9450717	best: 0.9450717 (195)	total: 17.8s	remaining: 26.5s
250:	learn: 0.9475110	test: 0.9472078	best: 0.9472078 (248)	total: 21.1s	remaining: 20.9s
300:	learn: 0.9497234	test: 0.9469027	best: 0.9475130 (254)	total: 25.8s	remaining: 17.1s
350:	learn: 0.9515545	test: 0.9473604	best: 0.9476655 (343)	total: 28.9s	remaining: 12.3s
400:	learn: 0.9533473	test: 0.9475130	best: 0.9476655 (343)	total: 32.2s	remaining: 7.95s
450:	learn: 0.9540340	test: 0.9469027	best: 0.9476655 (343)	total: 36.5s	remaining: 3.97s
499:	learn: 0.9554835	test: 0.9470552	best: 0.9476655 (343)	total: 40.3s	remaining: 0us

bestTest = 0.9476655478
bestIteration = 343

Shrink model to first 344 iterations.
Accuracy: 0.9476655477570949